services:
  api:
    image: faro-api:dev
    pull_policy: never
    build:
      context: .
      dockerfile: docker/Dockerfile.backend

  ui:
    image: faro-ui:dev
    pull_policy: never
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend

  dns:
    image: faro-dns:dev
    pull_policy: never
    build:
      context: .
      dockerfile: docker/Dockerfile.coredns
