package coredns

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync/atomic"
	"text/template"

	"github.com/derek/faro/internal/db"
)

var reloadTotal atomic.Uint64
var reloadFailedTotal atomic.Uint64

type Manager struct {
	Store     *db.Store
	ConfigDir string
}

type renderState struct {
	Upstreams    []string
	CacheEnabled bool
	CacheTTL     int
	DenialTTL    int
}

type RuleMatch struct {
	Kind string `json:"kind"`
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type LocalRecordMatch struct {
	ID    int64  `json:"id"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

type DomainDecision struct {
	Action       string            `json:"action"`
	Reason       string            `json:"reason"`
	Allowlist    *RuleMatch        `json:"allowlist,omitempty"`
	ManualBlock  *RuleMatch        `json:"manual_block,omitempty"`
	Blocklists   []RuleMatch       `json:"blocklists,omitempty"`
	LocalRecord  *LocalRecordMatch `json:"local_record,omitempty"`
	Confidence   string            `json:"confidence,omitempty"`
	CapturedAt   string            `json:"captured_at,omitempty"`
	Upstream     string            `json:"upstream,omitempty"`
	ResponseCode string            `json:"response_code,omitempty"`
}

func NewManager(store *db.Store, configDir string) *Manager {
	return &Manager{Store: store, ConfigDir: configDir}
}

func (m *Manager) Apply(ctx context.Context) error {
	reloadTotal.Add(1)
	state, err := m.render(ctx)
	if err != nil {
		reloadFailedTotal.Add(1)
		return err
	}
	if err := os.MkdirAll(m.ConfigDir, 0o755); err != nil {
		reloadFailedTotal.Add(1)
		return err
	}

	files := map[string][]byte{
		"Corefile":        []byte(state.Corefile),
		"faro.hosts":      []byte(state.LocalHosts + "\n" + state.BlockHosts),
		"local.hosts":     []byte(state.LocalHosts),
		"blocklist.hosts": []byte(state.BlockHosts),
	}
	if err := validate(files); err != nil {
		reloadFailedTotal.Add(1)
		return err
	}
	if err := replaceWithRollback(m.ConfigDir, files); err != nil {
		reloadFailedTotal.Add(1)
		return err
	}
	return nil
}

func ReloadTotals() (uint64, uint64) {
	return reloadTotal.Load(), reloadFailedTotal.Load()
}

type renderedFiles struct {
	Corefile   string
	LocalHosts string
	BlockHosts string
}

func (m *Manager) render(ctx context.Context) (renderedFiles, error) {
	settings, err := settingsMap(ctx, m.Store)
	if err != nil {
		return renderedFiles{}, err
	}
	upstreams := splitCSV(settings["upstream_dns"])
	if len(upstreams) == 0 {
		upstreams = []string{"1.1.1.1", "9.9.9.9"}
	}
	cacheEnabled := settings["dns_cache_enabled"] != "false"
	cacheTTL := 300
	if parsed, parseErr := strconv.Atoi(settings["dns_cache_ttl"]); parseErr == nil {
		cacheTTL = max(30, min(parsed, 3600))
	}
	denialTTL := min(cacheTTL, 60)

	localHosts, err := m.localHosts(ctx)
	if err != nil {
		return renderedFiles{}, err
	}
	blockHosts, err := m.blockHosts(ctx)
	if err != nil {
		return renderedFiles{}, err
	}

	corefileTemplate := template.Must(template.New("Corefile").Parse(`.:53 {
    errors
    metadata
    log . "FARO|{remote}|{type}|{name}|{rcode}|{duration}|{/forward/upstream}"
    prometheus 0.0.0.0:9153
    reload 2s
    hosts /etc/coredns/faro.hosts {
        ttl 60
        fallthrough
    }
    {{ if .CacheEnabled }}cache {{ .CacheTTL }} {
        success 9984 {{ .CacheTTL }} 5
        denial 4096 {{ .DenialTTL }} 5
    }
    {{ end }}forward . {{ range .Upstreams }}{{ . }} {{ end }}
}
`))
	var core bytes.Buffer
	if err := corefileTemplate.Execute(&core, renderState{Upstreams: upstreams, CacheEnabled: cacheEnabled, CacheTTL: cacheTTL, DenialTTL: denialTTL}); err != nil {
		return renderedFiles{}, err
	}
	return renderedFiles{
		Corefile:   core.String(),
		LocalHosts: localHosts,
		BlockHosts: blockHosts,
	}, nil
}

func (m *Manager) localHosts(ctx context.Context) (string, error) {
	rows, err := m.Store.DB.QueryContext(ctx, `SELECT hostname, type, value FROM dns_records ORDER BY hostname`)
	if err != nil {
		return "", err
	}
	defer rows.Close()

	var b strings.Builder
	b.WriteString("# Generated by Faro. Manual edits will be replaced.\n")
	for rows.Next() {
		var host, typ, value string
		if err := rows.Scan(&host, &typ, &value); err != nil {
			return "", err
		}
		if typ == "A" || typ == "AAAA" {
			fmt.Fprintf(&b, "%s %s\n", value, host)
		}
		// TODO: Render CNAME records through a CoreDNS plugin that supports aliases safely.
	}
	return b.String(), rows.Err()
}

func (m *Manager) blockHosts(ctx context.Context) (string, error) {
	allowlist, err := domains(ctx, m.Store, `SELECT domain FROM allowlist_entries`)
	if err != nil {
		return "", err
	}
	blocked, err := domains(ctx, m.Store, `
		SELECT domain FROM manual_block_entries
		UNION
		SELECT e.domain
		FROM blocklist_entries e
		JOIN blocklists b ON b.id = e.blocklist_id
		WHERE b.enabled = 1
	`)
	if err != nil {
		return "", err
	}

	allowed := map[string]struct{}{}
	for _, domain := range allowlist {
		allowed[domain] = struct{}{}
	}

	var b strings.Builder
	b.WriteString("# Generated by Faro. Allowlist entries are excluded.\n")
	for _, domain := range blocked {
		if _, ok := allowed[domain]; ok {
			continue
		}
		fmt.Fprintf(&b, "0.0.0.0 %s\n", domain)
	}
	return b.String(), nil
}

func settingsMap(ctx context.Context, store *db.Store) (map[string]string, error) {
	rows, err := store.DB.QueryContext(ctx, `SELECT key, value FROM settings`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := map[string]string{}
	for rows.Next() {
		var key, value string
		if err := rows.Scan(&key, &value); err != nil {
			return nil, err
		}
		result[key] = value
	}
	return result, rows.Err()
}

func domains(ctx context.Context, store *db.Store, query string, args ...any) ([]string, error) {
	rows, err := store.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var result []string
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		result = append(result, domain)
	}
	sort.Strings(result)
	return result, rows.Err()
}

func splitCSV(value string) []string {
	parts := strings.Split(value, ",")
	var result []string
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed != "" {
			result = append(result, trimmed)
		}
	}
	return result
}

func validate(files map[string][]byte) error {
	corefile := string(files["Corefile"])
	if !strings.Contains(corefile, ".:53") || !strings.Contains(corefile, "forward .") {
		return fmt.Errorf("generated Corefile is missing required server or forward block")
	}
	// TODO: Run `coredns -conf <temp Corefile> -dns.port=0` when the binary is available in the API container.
	return nil
}

func replaceWithRollback(dir string, files map[string][]byte) error {
	backups := map[string][]byte{}
	for name := range files {
		path := filepath.Join(dir, name)
		if existing, err := os.ReadFile(path); err == nil {
			backups[name] = existing
		} else if !os.IsNotExist(err) {
			return err
		}
	}

	written := []string{}
	for name, content := range files {
		tmp, err := os.CreateTemp(dir, "."+name+".*.tmp")
		if err != nil {
			rollback(dir, backups, written)
			return err
		}
		tmpName := tmp.Name()
		if _, err := tmp.Write(content); err != nil {
			_ = tmp.Close()
			_ = os.Remove(tmpName)
			rollback(dir, backups, written)
			return err
		}
		if err := tmp.Close(); err != nil {
			_ = os.Remove(tmpName)
			rollback(dir, backups, written)
			return err
		}
		if err := os.Chmod(tmpName, 0o644); err != nil {
			_ = os.Remove(tmpName)
			rollback(dir, backups, written)
			return err
		}
		target := filepath.Join(dir, name)
		if err := os.Rename(tmpName, target); err != nil {
			_ = os.Remove(tmpName)
			rollback(dir, backups, written)
			return err
		}
		written = append(written, name)
	}
	return nil
}

func rollback(dir string, backups map[string][]byte, written []string) {
	for _, name := range written {
		path := filepath.Join(dir, name)
		if content, ok := backups[name]; ok {
			_ = os.WriteFile(path, content, 0o644)
		} else {
			_ = os.Remove(path)
		}
	}
}

func IsBlocked(ctx context.Context, store *db.Store, domain string) (bool, string) {
	decision := ExplainDomain(ctx, store, domain)
	if decision.Action != "blocked" {
		if decision.Allowlist != nil {
			return false, "allowlist"
		}
		return false, "unknown"
	}
	if decision.ManualBlock != nil {
		return true, "manual"
	}
	return true, "blocklist"
}

func ExplainDomain(ctx context.Context, store *db.Store, domain string) DomainDecision {
	normalized, err := db.NormalizeDomain(domain)
	if err != nil {
		return DomainDecision{Action: "allowed"}
	}
	decision := DomainDecision{Action: "allowed"}
	var allowID int64
	if err := store.DB.QueryRowContext(ctx, `SELECT id FROM allowlist_entries WHERE domain = ?`, normalized).Scan(&allowID); err == nil {
		decision.Allowlist = &RuleMatch{Kind: "allowlist", ID: allowID, Name: "Manual allowlist"}
	}

	var manualID int64
	if err := store.DB.QueryRowContext(ctx, `SELECT id FROM manual_block_entries WHERE domain = ?`, normalized).Scan(&manualID); err == nil {
		decision.ManualBlock = &RuleMatch{Kind: "manual_block", ID: manualID, Name: "Manual domain block"}
	}

	rows, err := store.DB.QueryContext(ctx, `
		SELECT b.id, b.name
		FROM blocklist_entries e
		JOIN blocklists b ON b.id = e.blocklist_id
		WHERE b.enabled = 1 AND e.domain = ?
		ORDER BY b.name
	`, normalized)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var match RuleMatch
			match.Kind = "blocklist"
			if rows.Scan(&match.ID, &match.Name) == nil {
				decision.Blocklists = append(decision.Blocklists, match)
			}
		}
	}

	var local LocalRecordMatch
	if err := store.DB.QueryRowContext(ctx, `SELECT id, type, value FROM dns_records WHERE hostname = ? ORDER BY id LIMIT 1`, normalized).Scan(&local.ID, &local.Type, &local.Value); err == nil {
		decision.LocalRecord = &local
	}

	switch {
	case decision.Allowlist != nil:
		decision.Reason = "A manual allowlist exception bypassed filtering."
	case decision.ManualBlock != nil:
		decision.Action = "blocked"
		decision.Reason = "Matched a manual domain block."
	case len(decision.Blocklists) == 1:
		decision.Action = "blocked"
		decision.Reason = "Matched the " + decision.Blocklists[0].Name + " blocklist."
	case len(decision.Blocklists) > 1:
		decision.Action = "blocked"
		decision.Reason = fmt.Sprintf("Matched %d enabled blocklists.", len(decision.Blocklists))
	case decision.LocalRecord != nil:
		decision.Reason = "Matched a Faro Local DNS record."
	}
	return decision
}
