FROM coredns/coredns:1.11.3 AS coredns

FROM --platform=$BUILDPLATFORM golang:1.22-bookworm AS logtee-build

ARG TARGETOS
ARG TARGETARCH

WORKDIR /src
COPY go.mod ./
COPY cmd/faro-logtee ./cmd/faro-logtee
RUN CGO_ENABLED=0 GOOS="$TARGETOS" GOARCH="$TARGETARCH" go build -o /out/faro-logtee ./cmd/faro-logtee

FROM alpine:3.20

RUN adduser -D -H coredns
COPY --from=coredns /coredns /usr/local/bin/coredns
COPY --from=logtee-build /out/faro-logtee /usr/local/bin/faro-logtee
RUN mkdir -p /etc/coredns /var/log/coredns && chown -R coredns:coredns /etc/coredns /var/log/coredns
USER coredns
EXPOSE 53 53/udp
ENTRYPOINT ["/bin/sh", "-c"]
CMD ["coredns -conf /etc/coredns/Corefile 2>&1 | faro-logtee --path /var/log/coredns/query.log --max-bytes ${FARO_QUERY_LOG_MAX_BYTES:-10485760} --backups ${FARO_QUERY_LOG_BACKUPS:-2}"]
