FROM golang:1.25-bookworm AS air

ARG AIR_VERSION=v1.65.1
RUN go install github.com/air-verse/air@${AIR_VERSION}

FROM golang:1.22-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
COPY --from=air /go/bin/air /usr/local/bin/air

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
